### ISSUE TITLE
TP357 Battery Status

### ISSUE THREAD

**Issue by saxesn** [Bluetooth-Devices/thermopro-ble#11]
Does your feature request relate to a problem? Please describe it.

There is no battery status query for the TP357 devices, it would be nice if this could be added. I have matched the data from BLE Analyzer with the data from the IOS app.

Describe the solution you would like to see.

In each data set, the seventh byte (when we start counting at 1) is different and seems to correspond to the battery status of the app. It looks like "0" represents low battery status, "2" represents high battery status, and "1" represents half full battery status.

Can anyone confirm this?

I have collected data from several thermometers:

id=9A57 #07FFC2E50032002C0000  [7, 255, 194, 229, 0, 50, **0**, 44, 0, 0] battery low tmp 22.9 humi=50
id=8ff9  #07FFC2E00036022C0000    [7, 255, 194, 224, 0, 54, **2,** 44, 0, 0] Battery high tmp 22.4 humi=54
id=3e17  #07FFC2EE0033012C0000   [7, 255, 194, 238, 0, 51, **1**, 44, 0, 0] Battery half full tmp 23.8 humi=51
id=3e17  #07FFC2EF002F012C0000    [7, 255, 194, 239, 0, 47, **1,** 44, 0, 0] battery half full   tmp 23,9 humi=47

**Comment by bdraco** [comment]
seem to hold true for mine so lets add it

**Comment by bdraco** [comment]
If you open a PR to HA to add the battery sensor, I'm pretty sure we can get it merged before next months release.
